spark.driver.memory              1g
spark.executor.memory            1g
spark.executor.cores             1

spark.sql.shuffle.partitions     4
spark.default.parallelism        4

spark.sql.extensions             org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions


spark.driver.extraClassPath      /opt/spark/jars/custom/*
spark.executor.extraClassPath    /opt/spark/jars/custom/*

# ============================================================
# ICEBERG + NESSIE
# ============================================================

spark.sql.catalog.iceberg_catalog                     org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.iceberg_catalog.type                rest
spark.sql.catalog.iceberg_catalog.uri                 http://nessie:19120/iceberg
spark.sql.catalog.iceberg_catalog.warehouse           warehouse

# ============================================================
# MINIO / S3
# ============================================================

spark.hadoop.fs.s3a.endpoint                       http://minio:9000
spark.hadoop.fs.s3a.access.key                     minioadmin
spark.hadoop.fs.s3a.secret.key                      minioadmin
spark.hadoop.fs.s3a.path.style.access               true
spark.hadoop.fs.s3a.connection.ssl.enabled          false
spark.hadoop.fs.s3a.impl                            org.apache.hadoop.fs.s3a.S3AFileSystem